apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata: 
  name: train-schedule
  region: us-east-2
nodeGroups: 
  allow: false
  desiredCapacity: 3
  instanceType: t2.medium
  name: ng-1
  ssh: ~
